INSERT INTO Prueba_medica(prueba_medica) VALUES('Amniocentesis (análisis del líquido amniótico)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Amplitud de distribución eritrocitaria');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de cálculos renales');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de globulinas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de hemoglobina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de sangre de glucagón');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de sangre de la brecha aniónica');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de sangre de lipoproteína (a)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis de semen');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis del complemento');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis del líquido cefalorraquídeo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis del líquido pleural');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Análisis del líquido sinovial');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Anoscopia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Anticuerpos antitiroideos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Ayuno para exámenes de sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Biopsia de ganglio centinela');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Biopsia de piel');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Biopsia de seno');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Broncoscopia con lavado broncoalveolar');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cadenas ligeras libres');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cociente de microalbúmina y creatinina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Colposcopia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cómo afrontar la ansiedad causada por los exámenes médicos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cómo entender el resultado de sus pruebas de laboratorio');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cómo preparar a su hijo para una prueba de laboratorio');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cómo prepararse para una prueba de laboratorio');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Conteo de glóbulos blancos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Conteo de glóbulos rojos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Conteo de reticulocitos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Conteo sanguíneo completo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Creatina cinasa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Cultivo de esputo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Densitometría ósea');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Diagnóstico diferencial');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Dióxido de carbono (CO2) en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Ecografía');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Ecografía Doppler');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Elastasa fecal');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Elastografía');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Electrocardiograma');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Electroforesis de hemoglobina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Electromiografía y estudios de conducción nerviosa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Estudio del sueño');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de depresión');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de la depresión posparto');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de obesidad');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de quemaduras');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de salud mental');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de sarpullido');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de trastornos del espectro alcohólico fetal (TEAF)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación de trastornos del espectro autista (TEA)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación del consumo de alcohol');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación del riesgo de caídas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación del riesgo de enfermedad cardíaca');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación del riesgo de suicidio');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Evaluación del TDAH');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen de bilirrubina en sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen de cáncer de piel');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen de isoenzimas de la lactato deshidrogenasa (LDH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen de la vista');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen de nitrógeno ureico en sangre (NUS)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen del pie diabético');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen dental');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Examen neurológico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Fluoroscopia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Fórmula leucocitaria');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Fosfatasa alcalina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Frotis de sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Gammagrafía V/Q');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Glóbulos blancos en las heces');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Hematocrito');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Hisopado nasal');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Histeroscopia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Hormona adrenocorticotrópica (ACTH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Índice de IgG en LCR');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Índices de glóbulos rojos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Insulina en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Ionograma');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Laparoscopia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Marcadores tumorales');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Medición de la presión arterial');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Mielografía');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Monitorización de fármacos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Muestra de vellosidades coriónicas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Nivel de acetaminofén');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Nivel de salicilatos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Niveles de amoníaco');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Niveles de colesterol');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Niveles de prolactina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Panel de patógenos respiratorios');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Panel metabólico básico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Panel metabólico completo (PMC)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pielografía intravenosa (PIV)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Proteínas totales y relación albúmina/globulina (A/G)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ACE');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ácido láctico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ácido metilmalónico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ácido úrico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ADN fetal libre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de AFP (alfafetoproteína)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de albúmina en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de alcohol en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de aldosterona');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de alergias');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de alergias en la piel');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de alfa-1 antitripsina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de amilasa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de anticuerpos antinucleares');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de anticuerpos antipéptido cíclico citrulinado (anti-CCP)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de anticuerpos contra el músculo liso');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de anticuerpos contra los glóbulos rojos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de anticuerpos frente al citoplasma de los neutrófilos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de antidepresivos tricíclicos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de antígeno de cáncer 125 (para cáncer de ovario)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de AST');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de calcio en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de calcio en orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de calcitonina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cáncer de seno HER2');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de carga viral');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cariotipo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de CA-19-9 en sangre (cáncer de páncreas)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de ceruloplasmina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cetonas en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cetonas en sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de clamidia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cloruro en sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cortisol');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de creatinina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cristales en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cultivo de bacterias');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de cultivo fúngico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de detección de fenilcetonuria (FCU)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de embarazo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de enfermedad celíaca');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de estimulación por frío');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de estreptococos A');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de estreptococos del grupo B');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de estrógeno');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de factor reumatoideo (FR)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de fosfato en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de fosfato en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de galactosemia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de gamma-glutamil transferasa (GGT)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de gasometría arterial');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de glucosa en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de glucosa en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de gonorrea');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de G6PD');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de haptoglobina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de hemoglobina A1c');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de hepatitis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de homocisteína');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de hormona paratiroidea (PTH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de huevos y parásitos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de IGF-1 (factor de crecimiento similar a la insulina 1)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de inmunofijación');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de la fiebre del dengue');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de la gripe (influenza)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de la hormona antimulleriana');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de la médula ósea');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de lactato deshidrogenasa (LDH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de lipasa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de magnesio en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de marcador tumoral AFP (alfafetoproteína)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de marcador tumoral de microglobulina Beta-2 (B2M)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de marcadores tumorales de cáncer de pulmón');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de moco en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de mutaciones de MTHFR');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de nitritos en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de niveles de la hormona foliculoestimulante (FSH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de niveles de la hormona luteinizante (HL)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de niveles de testosterona');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de Papanicolaou');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de parainfluenza');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de PD-L1 (inmunoterapia)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de péptido C');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de pH esofágico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de potasio en sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de procalcitonina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de progesterona');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de proteína C reactiva (PCR)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de proteínas en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de PSA (antígeno prostático específico)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de renina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de ALT');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de ferritina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de inmunoglobulinas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de metales pesados');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de prealbúmina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de SHBG');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de VCM');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre de VPM');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sangre oculta en heces');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sensibilidad a los antibióticos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de síndrome de Down');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sodio en la sangre');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sudor');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de sulfato de DHEA');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tasa de filtración glomerular (TFG)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tiempo de protrombina e INR (TP/INR)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tiroxina (T4)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tos ferina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de TPT (tiempo parcial de tromboplastina)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tricomoniasis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de triglicéridos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de troponina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de TSH');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de tuberculosis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de uribilinógeno en orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de vaginosis bacteriana');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de varicela y herpes zóster');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de VIH');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de vitamina B');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de vitamina D');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba de vitamina E (tocoferol)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del dímero D');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del trastorno de pánico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del trastorno obsesivo-compulsivo (TOC)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del virus del herpes simple (VHS)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del virus del papiloma humano (VPH)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del virus del Zika');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba del virus sincicial respiratorio (VSR)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba genética BCR-ABL');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba genética de BRCA');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba genética del BRAF');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba genética del PTEN');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba genética TP 53 (proteína tumoral 53)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Prueba sin estrés');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas autonómicas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas cognitivas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de alergias alimentarias');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de apendicitis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de audición para adultos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de audición para niños');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de bacilos acidorresistentes (BAAR)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de bilirrubina en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de C. difficile');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de catecolaminas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de células epiteliales en la orina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de citomegalovirus (CMV)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de conmoción cerebral');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de detección de cáncer colorrectal');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de detección del uso de drogas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de diabetes');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de disfagia');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de drogas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de enfermedades de transmisión sexual (ETS)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de esfuerzo');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de evaluación del desarrollo y el comportamiento');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de función pulmonar');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de glaucoma');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de Helicobacter pylori (H. Pylori)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de hierro');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de la enfermedad de Lyme');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de la hormona del crecimiento');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de legionela');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de los factores de la coagulación');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de malaria');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de miastenia grave (MG)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de mononucleosis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de opiáceos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de osmolalidad');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de PCR');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de péptidos natriuréticos (BNP, NT-proBNP)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de plaquetas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de porfirina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de proteína C y proteína S');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de receptores de estrógeno y de progesterona');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de sarampión y paperas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de SARM');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de serología de anticuerpos');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de sífilis');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de tolerancia a la lactosa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de triyodotironina (T3)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de vaciamiento gástrico');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas de xilosa');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas del equilibrio');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas farmacogenéticas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas funcionales hepáticas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas médicas en el hogar');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas para detectar infecciones por cándida');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas prenatales');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas rápidas');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pruebas y bancos de sangre del cordón umbilical');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Pulsioximetría');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Quimotripsina en heces');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Recuento de linfocitos CD4');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Tasa de sedimentación eritrocítica');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Tinción de Gram');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Tiroglobulina');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Tomografía por emisión de positrones');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Tránsito esofagogastroduodenal');
INSERT INTO Prueba_medica(prueba_medica) VALUES('Videonistagmografía (VNG)');
INSERT INTO Prueba_medica(prueba_medica) VALUES('17-hidroxiprogesterona');
